### PR TITLE
Added tool 'Col Name to ObjName(DataName)'

### PR DESCRIPTION
**Pull request by Oxicid**
Added the ability to apply a collection name to an object. Also the tool 'Obj Name to Data Name' now skips the instance objects, only the name of the first instance object is applied to the object data

### CODE REVIEW

**Comment by mrven** [comment]
Thank you for PR! Sorry for long review. I manually moved the changes to a future version. I learned a lot of new things from your PR

**Comment by Oxicid** [comment]
> Спасибо за пиар! Извините за долгий отзыв. Я вручную перенес изменения в будущую версию. Я узнал много нового из твоего пиара

PR was written when I first started learning Python. There is a lot of nesting of loops and conditional expressions in the code, and I probably shouldn't have added an object type to the name.

 Also camelcase and double underscore are used in names, and comments are also written in expressions themselves, not on a separate line, in short it's horrible :).

**Comment by Oxicid** [comment]
> Thank you for PR! Sorry for long review. I manually moved the changes to a future version. I learned a lot of new things from your PR

PR was written when I first started learning Python. There is a lot of nesting of loops and conditional expressions in the code, and I probably shouldn't have added an object type to the name.

 Also camelcase and double underscore are used in names, and comments are also written in expressions themselves, not on a separate line, in short it's horrible :).

**Comment by mrven** [comment]
Я добавлю опций для этой функции и исправлю код под общий для проекта code style guide))

**Pull request closed without merging**
